kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mcp-governance
nodes:
  - role: control-plane
    image: kindest/node:v1.34.0
    extraPortMappings:
      - containerPort: 30000
        hostPort: 3000
        protocol: TCP
      - containerPort: 8080
        hostPort: 80
        protocol: TCP
      - containerPort: 8443
        hostPort: 443
        protocol: TCP
