{{- if .Values.controller.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcp-governance.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mcp-governance.controllerLabels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
